import type { RiskLevel, SecurityDecision } from '@/features/firewall'
import { apiClient } from '@/services/api'
import type { AgentActionReason } from './authorizeAgentAction'

/** How the tool gateway handled a request: whether the tool ran and, if not, which stage stopped it. */
export type ToolExecutionOutcome =
  | 'Executed'
  | 'HeldForReview'
  | 'Denied'
  | 'ArgumentsRejected'
  | 'ToolUnavailable'
  | 'ExecutionAuthorizationRejected'
  | 'ExecutionFailed'
  | 'InputContextRejected'
  | 'ApprovalRejected'

/**
 * A tool call for the gateway. There is no agent field: the agent is the one the API key identifies. There is no field for
 * a decision, grants or an execution authorization either; the API rejects any (400).
 */
export interface ToolExecutionRequest {
  tool: string
  action: string
  /** The capability the agent claims authorises the action, `resource:operation`. */
  capability: string
  /** The tool's arguments, a JSON object. For `knowledge.lookup`: `{ query }`, 1–200 characters. */
  arguments: Readonly<Record<string, unknown>>
  /** The caller's report of the firewall's decision on the input behind the call; it can only make the decision stricter. */
  inputDecision?: SecurityDecision
  /**
   * The security event of the firewall analysis of the input behind the call. The gateway uses its own record of that
   * analysis (this client's, in this trace, recent): its decision applies whatever `inputDecision` claims.
   */
  inputEventId?: string
  /** A person's approval of exactly this call, after the gateway held it: authorises one execution. */
  approvalId?: string
}

/** The tool's result when it ran. The reference tool's text comes from its own fixed dataset, never from the request. */
export interface ToolResult {
  found: boolean
  text: string | null
}

/** What the gateway did. Only `Allow` with `executed` means the tool ran; nothing else ever does. */
export interface ToolExecution {
  securityEventId: string
  decision: SecurityDecision
  executed: boolean
  outcome: ToolExecutionOutcome
  /** The authorization boundary's reason for its verdict on the action. */
  authorizationReason: AgentActionReason
  riskLevel: RiskLevel
  /** An audit identifier when an execution grant was issued; not a credential. */
  executionId: string | null
  result: ToolResult | null
  /**
   * For a held call the gateway can run: the pending approval created for it. For a call that ran after approval: the
   * approval it used. For a rejected approval: the one presented. `null` otherwise.
   */
  approvalId: string | null
}

/**
 * POST /api/v1/agent/tools/execute: asks the tool gateway to run a tool action for the agent the API key identifies. Every
 * decision (Block included) is a 200 response, and every stage is recorded. Requires the `tool:execute` permission.
 */
export function executeTool(request: ToolExecutionRequest, signal?: AbortSignal): Promise<ToolExecution> {
  return apiClient.post<ToolExecution>('/api/v1/agent/tools/execute', request, { signal })
}

/** A tool execution together with the response metadata needed to trace it. */
export interface ToolExecutionResult {
  execution: ToolExecution
  /** Request trace ID (`meta.correlationId`), generated by the API; distinct from the security event ID. */
  correlationId: string
  /** When the API produced the response (`meta.timestamp`, ISO 8601). */
  timestamp: string
}

/**
 * {@link executeTool}, keeping the response's correlation ID and timestamp. `correlationId` sends the call in a given trace
 * (the trace of the input analysis it references, which the gateway requires).
 */
export async function executeToolTraced(request: ToolExecutionRequest, signal?: AbortSignal, correlationId?: string): Promise<ToolExecutionResult> {
  const { data, meta } = await apiClient.postForEnvelope<ToolExecution>('/api/v1/agent/tools/execute', request, {
    signal,
    headers: correlationId === undefined ? undefined : { 'X-Correlation-ID': correlationId },
  })
  return { execution: data, correlationId: meta.correlationId, timestamp: meta.timestamp }
}
